In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
df = pd.read_csv('./dummy_silver_data.csv')

In [5]:
df.shape

(16176, 9)

In [6]:
df.columns

Index(['location_id', 'sensor_id', 'location_name', 'datetime_utc', 'lat',
       'lon', 'parameter', 'value', 'unit'],
      dtype='str')

In [7]:
df.dtypes

location_id          str
sensor_id            str
location_name        str
datetime_utc         str
lat              float64
lon              float64
parameter            str
value            float64
unit                 str
dtype: object

In [8]:
df.memory_usage(deep=True)

Index                132
location_id       873504
sensor_id         873504
location_name    1063572
datetime_utc     1116144
lat               129408
lon               129408
parameter         841152
value             129408
unit             1132320
dtype: int64

In [9]:
df.head()

,location_id,sensor_id,location_name,datetime_utc,lat,lon,parameter,value,unit
0,AU001,S0001,Sydney - Rozelle,2026-08-06T00:00:00Z,-33.8608,151.1719,o3,8.59,µg/m³
1,AU001,S0001,Sydney - Rozelle,2026-08-06T00:00:00Z,-33.8608,151.1719,no2,17.90,µg/m³
2,AU001,S0001,Sydney - Rozelle,2026-08-06T00:00:00Z,-33.8608,151.1719,pm25,9.06,µg/m³
3,AU001,S0001,Sydney - Rozelle,2026-08-06T01:00:00Z,-33.8608,151.1719,o3,17.31,µg/m³
4,AU001,S0001,Sydney - Rozelle,2026-08-06T01:00:00Z,-33.8608,151.1719,no2,20.44,µg/m³

In [10]:
df.tail()

,location_id,sensor_id,location_name,datetime_utc,lat,lon,parameter,value,unit
16171,AU008,S0021,Darwin - Palmerston,2026-08-19T23:00:00Z,-12.4855,130.982,so2,5.74,µg/m³
16172,AU008,S0021,Darwin - Palmerston,2026-08-19T23:00:00Z,-12.4855,130.982,no2,38.36,µg/m³
16173,AU008,S0021,Darwin - Palmerston,2026-08-20T00:00:00Z,-12.4855,130.982,pm10,9.87,µg/m³
16174,AU008,S0021,Darwin - Palmerston,2026-08-20T00:00:00Z,-12.4855,130.982,so2,7.29,µg/m³
16175,AU008,S0021,Darwin - Palmerston,2026-08-20T00:00:00Z,-12.4855,130.982,no2,30.73,µg/m³

In [11]:
df.sample(n=5)

,location_id,sensor_id,location_name,datetime_utc,lat,lon,parameter,value,unit
13682,AU007,S0019,Hobart - New Town,2026-08-10T05:00:00Z,-42.8613,147.3080,no2,15.55,µg/m³
6637,AU004,S0008,Perth - Swanbourne,2026-08-17T21:00:00Z,-31.9614,115.7714,so2,3.54,µg/m³
4005,AU002,S0004,Melbourne - CBD,2026-08-19T12:00:00Z,-37.8136,144.9631,pm10,16.46,µg/m³
15396,AU008,S0021,Darwin - Palmerston,2026-08-09T05:00:00Z,-12.4855,130.9820,pm10,15.93,µg/m³
7047,AU004,S0009,Perth - Swanbourne,2026-08-12T09:00:00Z,-31.9614,115.7714,no2,21.37,µg/m³

In [12]:
df.nunique()

location_id         8
sensor_id          21
location_name       8
datetime_utc      337
lat                 8
lon                 8
parameter           6
value            7471
unit                1
dtype: int64

In [13]:
df['location_name'].value_counts()

location_name
Sydney - Rozelle       2022
Melbourne - CBD        2022
Brisbane - South       2022
Perth - Swanbourne     2022
Adelaide - Netley      2022
Canberra - Civic       2022
Hobart - New Town      2022
Darwin - Palmerston    2022
Name: count, dtype: int64

In [15]:
print("First record date: ", df['datetime_utc'].min())

First record date:  2026-08-06T00:00:00Z

In [16]:
print("First record date: ", df['datetime_utc'].max())

First record date:  2026-08-20T00:00:00Z