In [12]:
import pandas as pd

# Read a single Parquet file
layer1_quality_sensor_metrics = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer1\quality_sensor_metrics\locationid=1601414\year=2026\part-0.parquet')
layer1_quality_sensor_metrics.head()

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
C:\Users\shahs\AppData\Local\Temp\ipykernel_9340\1120528713.py:4: SyntaxWarning: invalid escape sequence '\C'
  layer1_quality_sensor_metrics = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer1\quality_sensor_metrics\locationid=1601414\year=2026\part-0.parquet')

,locationid,sensor_id,parameter,date_local,readings_received,readings_expected,missing_rate,null_value_count,negative_count,duplicate_count,max_stuck_run,value_variance,unit_mismatch
0,1601414,7006174,pm25,2026-01-01,23,24,0.041667,0,0,0,1,10.750258,0
1,1601414,7006174,pm25,2026-01-02,24,23,0.000000,0,0,0,3,177.332427,0
2,1601414,7006174,pm25,2026-01-03,24,24,0.000000,0,0,0,2,191.012662,0
3,1601414,7006174,pm25,2026-01-04,23,24,0.041667,0,0,0,2,2.179824,0
4,1601414,7006174,pm25,2026-01-05,24,24,0.000000,0,0,0,1,21.008538,0

In [11]:
import pandas as pd

# Read a single Parquet file
layer2_event_alerts = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer2\event_alerts\locationid=1601414\year=2026\part-0.parquet')

# # Read a partitioned dataset directory
# df = pd.read_parquet('path/to/dataset_directory/')
layer2_event_alerts.head(3)

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
C:\Users\shahs\AppData\Local\Temp\ipykernel_9340\4133671955.py:4: SyntaxWarning: invalid escape sequence '\C'
  layer2_event_alerts = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer2\event_alerts\locationid=1601414\year=2026\part-0.parquet')

,locationid,date_local,parameter,region_id,alert_score,rank,if_flag,lof_flag,dbscan_flag,agreement_count,weak_label,feature_snapshot
0,1601414,2026-01-01,pm25,sydney_metro,0.353437,5,False,False,False,1,False,"{""locationid"": 1601414, ""date_local"": ""2026-01..."
1,1601414,2026-01-02,pm25,sydney_metro,1.259024,1,True,True,True,1,False,"{""locationid"": 1601414, ""date_local"": ""2026-01..."
2,1601414,2026-01-03,pm25,sydney_metro,1.163176,1,False,False,True,2,False,"{""locationid"": 1601414, ""date_local"": ""2026-01..."

In [10]:
import pandas as pd

# Read a single Parquet file
layer2_event_features = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer2\event_features\locationid=1544061\year=2026\part-0.parquet')
layer2_event_features.head()

<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
C:\Users\shahs\AppData\Local\Temp\ipykernel_9340\660849385.py:4: SyntaxWarning: invalid escape sequence '\C'
  layer2_event_features = pd.read_parquet('D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\layer2\event_features\locationid=1544061\year=2026\part-0.parquet')

,locationid,date_local,parameter,region_id,daily_mean,daily_max,z_score,iqr_exceedance,roc_max,spike_count,sustained_elevation_hours,mean_shift_ratio,peer_z_score,spatial_isolation,regional_agreement,pm_co_movement
0,1544061,2026-01-01,pm25,sydney_metro,3.287991,11.863095,0.089763,1.422751e+00,4.604167,0,1,1.306641,-0.334576,0.223051,0.333333,0.0
1,1544061,2026-01-02,pm25,sydney_metro,0.146391,0.688988,-3.141599,-2.599002e+06,0.562500,0,0,0.044523,-0.864681,0.576454,0.333333,0.0
2,1544061,2026-01-01,pm1,sydney_metro,1.519128,6.834821,0.095180,1.356319e+00,2.825893,0,1,1.535118,-1.000000,0.500000,0.500000,0.0
3,1544061,2026-01-02,pm1,sydney_metro,0.008185,0.087798,-1.510943,-1.431330e+06,0.087798,0,0,0.005388,-1.000000,1.000000,0.000000,0.0
4,1544061,2026-01-03,pm25,sydney_metro,0.390139,1.324107,-0.597382,-7.502444e-01,0.750000,0,0,0.227196,-0.917541,0.611694,0.333333,0.0

In [15]:
import pandas as pd
fusion_trust_alerts = pd.read_parquet(r'D:\CDU\Semester4\Data_Science_Practice\dataguard\data\gold\fusion\trust_alerts\locationid=1544061\year=2026\part-0.parquet')
fusion_trust_alerts.head()

,locationid,date_local,parameter,region_id,alert_score,rank,agreement_count,if_flag,lof_flag,dbscan_flag,weak_label,has_quality_incident,max_severity,incident_count,incident_rule_ids,trust_score,status,feature_snapshot
0,1544061,2026-01-01,pm25,sydney_metro,0.357399,3,1,False,False,False,False,False,,0,,0.357399,escalated,"{""locationid"": 1544061, ""date_local"": ""2026-01..."
1,1544061,2026-01-01,pm1,sydney_metro,0.356041,4,1,False,False,False,False,False,,0,,0.356041,escalated,"{""locationid"": 1544061, ""date_local"": ""2026-01..."
2,1544061,2026-01-02,pm25,sydney_metro,0.878935,3,2,False,True,False,False,True,high,1,R2,0.263680,quarantined,"{""locationid"": 1544061, ""date_local"": ""2026-01..."
3,1544061,2026-01-02,pm1,sydney_metro,0.822909,5,2,False,True,False,False,True,high,1,R2,0.246873,quarantined,"{""locationid"": 1544061, ""date_local"": ""2026-01..."
4,1544061,2026-01-03,pm1,sydney_metro,0.380655,2,1,False,False,False,False,False,,0,,0.380655,escalated,"{""locationid"": 1544061, ""date_local"": ""2026-01..."

,locationid,date_local,parameter,region_id,daily_mean,daily_max,z_score,iqr_exceedance,roc_max,spike_count,sustained_elevation_hours,mean_shift_ratio,peer_z_score,spatial_isolation,regional_agreement,pm_co_movement
0,1544061,2026-01-01,pm25,sydney_metro,3.287991,11.863095,0.089763,1.422751e+00,4.604167,0,1,1.306641,-0.334576,0.223051,0.333333,0.0
1,1544061,2026-01-02,pm25,sydney_metro,0.146391,0.688988,-3.141599,-2.599002e+06,0.562500,0,0,0.044523,-0.864681,0.576454,0.333333,0.0
2,1544061,2026-01-01,pm1,sydney_metro,1.519128,6.834821,0.095180,1.356319e+00,2.825893,0,1,1.535118,-1.000000,0.500000,0.500000,0.0
3,1544061,2026-01-02,pm1,sydney_metro,0.008185,0.087798,-1.510943,-1.431330e+06,0.087798,0,0,0.005388,-1.000000,1.000000,0.000000,0.0
4,1544061,2026-01-03,pm25,sydney_metro,0.390139,1.324107,-0.597382,-7.502444e-01,0.750000,0,0,0.227196,-0.917541,0.611694,0.333333,0.0